export const INTEREST_OPTIONS = [
  { id: 'tech', label: 'Technology', icon: '💻' },
  { id: 'gaming', label: 'Gaming', icon: '🎮' },
  { id: 'music', label: 'Music', icon: '🎵' },
  { id: 'sports', label: 'Sports', icon: '⚽' },
  { id: 'movies', label: 'Movies', icon: '🎬' },
  { id: 'art', label: 'Art', icon: '🎨' },
  { id: 'science', label: 'Science', icon: '🔬' },
  { id: 'travel', label: 'Travel', icon: '✈️' },
  { id: 'food', label: 'Food', icon: '🍕' },
  { id: 'fashion', label: 'Fashion', icon: '✨' },
  { id: 'fitness', label: 'Fitness', icon: '💪' },
  { id: 'business', label: 'Business', icon: '📈' },
  { id: 'coding', label: 'Coding', icon: '👨‍💻' },
  { id: 'anime', label: 'Anime', icon: '🍥' },
  { id: 'photography', label: 'Photography', icon: '📷' },
  { id: 'nature', label: 'Nature', icon: '🌿' },
  { id: 'books', label: 'Books', icon: '📚' },
  { id: 'education', label: 'Education', icon: '🎓' },
  { id: 'memes', label: 'Memes', icon: '🤪' },
  { id: 'cars', label: 'Cars', icon: '🚗' },
  { id: 'design', label: 'Design', icon: '✒️' },
  { id: 'history', label: 'History', icon: '🏛️' },
  { id: 'news', label: 'News', icon: '📰' },
  { id: 'crypto', label: 'Crypto', icon: '🪙' },
];
